/**
 * @type {string}
 * The location for all autogenerated views.
 */
const VIEWS_PATH = "Views";

/**
 * @type {string}
 * The location for all things and subfolders containing more things.
 */
const THINGS_PATH = "Things";

/**
 * If `renderViewsList()` renders initiated and uninitiated views mixed,
 * instead of having all the initiated before the uninitiated.
 * @type {boolean}
 */
const MERGE_VIEWS_IN_LIST = false;

const { regularViewMatchesTags } = require("./core.js");
/** @import { CustomTags, CustomViews } from "./core.js"; */

/** @type {CustomViews} */
const CUSTOM_VIEWS = {};

/** @type {CustomTags} */
const CUSTOM_TAGS = {};

module.exports = {
  VIEWS_PATH,
  THINGS_PATH,
  MERGE_VIEWS_IN_LIST,
  CUSTOM_VIEWS,
  CUSTOM_TAGS,
};
